---
title: "YNP_ungulate_indiv_habitat per point"
author: "Molly Caldwell"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE)
knitr::opts_knit$set(root.dir = "~/UWyo/PhD project/YNP-ungulate-niche-proj/")
```

```{r}
#packages
library(sf)
library(raster)
library(mapview)
library(tidyverse)
library(stringr)
library(move)
#library(dummies) #not available
library(lme4)
library(parallel)
library(lubridate)
```

#Load GPS Data

```{r}
#load seasonal GPS data with 2 hour fixes for all species
data <- readRDS("./Data/GPS data/Cleaned/allspp_cleanedGPSdata_seasonal_3.2022.rds")

data <- st_as_sf(data)

#add date only column
data <- data %>%
  mutate(date_only = format(date, format = "%Y-%m-%d"))

#remove extra date column
data$date2 <- NULL
```

#Relate GIS to points

```{r}
#bring in all your GIS data
elev <- raster("~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/Elevation_meters_30m_gye.tif")
trasp <- raster("~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/Aspect_TRASP_30m_gye.tif")
slope <- raster("~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/Slope_degrees_30m_gye.tif")
tpi <- raster("~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/TPI_unitless_30m_gye.tif")


#RAP data (forbs grass biomass and %cover by land cover type per year)
RAP_ann_biomass_file_list <- list.files(path = "~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/", 
                        pattern = glob2rx("*Biomass*AnnualForbsGrasses*"),
                        full.names = TRUE)

RAP_per_biomass_file_list <- list.files(path = "~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/", 
                        pattern = glob2rx("*Biomass*PerennialForbsGrasses*"),
                        full.names = TRUE)

RAP_treecov_file_list <- list.files(path = "~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/", 
                        pattern = glob2rx("*Cover_Trees*"),
                        full.names = TRUE)

RAP_shrubcov_file_list <- list.files(path = "~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/", 
                        pattern = glob2rx("*Cover_Shrubs*"),
                        full.names = TRUE)

RAP_ann_biomass_list <- list()
for(i in 1:length(RAP_ann_biomass_file_list)){
  print(i)
RAP_ann_biomass_list[[i]] <- raster(RAP_ann_biomass_file_list[[i]])
}

RAP_ann_biomass_names <- sub(".*RAP_gye_30m_reproj_", "", RAP_ann_biomass_file_list)
RAP_ann_biomass_names <- sub("*.tif", "", RAP_ann_biomass_names)
names(RAP_ann_biomass_list) <- RAP_ann_biomass_names

RAP_per_biomass_list <- list()
for(i in 1:length(RAP_per_biomass_file_list)){
  print(i)
RAP_per_biomass_list[[i]] <- raster(RAP_per_biomass_file_list[[i]])
}

RAP_per_biomass_names <- sub(".*RAP_gye_30m_reproj_", "", RAP_per_biomass_file_list)
RAP_per_biomass_names <- sub("*.tif", "", RAP_per_biomass_names)
names(RAP_per_biomass_list) <- RAP_per_biomass_names

RAP_treecov_list <- list()
for(i in 1:length(RAP_treecov_file_list)){
  print(i)
RAP_treecov_list[[i]] <- raster(RAP_treecov_file_list[[i]])
}

RAP_treecov_names <- sub(".*RAP_gye_30m_reproj_", "", RAP_treecov_file_list)
RAP_treecov_names <- sub("*.tif", "", RAP_treecov_names)
names(RAP_treecov_list) <- RAP_treecov_names

RAP_shrubcov_list <- list()
for(i in 1:length(RAP_shrubcov_file_list)){
  print(i)
RAP_shrubcov_list[[i]] <- raster(RAP_shrubcov_file_list[[i]])
}

RAP_shrubcov_names <- sub(".*RAP_gye_30m_reproj_", "", RAP_shrubcov_file_list)
RAP_shrubcov_names <- sub("*.tif", "", RAP_shrubcov_names)
names(RAP_shrubcov_list) <- RAP_shrubcov_names
```

```{r}
#add perennial and annual grass and forb biomass rasters by year
RAP_forbgrass_biomass <- list()

for(i in 1:length(RAP_per_biomass_list)){
  print(paste0("i: ", i))
  
  biomass_stack <- stack(RAP_ann_biomass_list[[i]], RAP_per_biomass_list[[i]])
  ann_per_biomass <-  calc(biomass_stack, sum)
  
  RAP_forbgrass_biomass[[i]] <- ann_per_biomass
}

names(RAP_forbgrass_biomass) <- c("forb_grass_biomass_2016", 
                                  "forb_grass_biomass_2017",
                                  "forb_grass_biomass_2018",
                                  "forb_grass_biomass_2019",
                                  "forb_grass_biomass_2020",
                                  "forb_grass_biomass_2021")

```


```{r}
# extract topographic GIS data to all points
data$elev <- raster::extract(elev, st_transform(data, crs=projection(elev)))
data$trasp <- raster::extract(trasp, st_transform(data, crs=projection(trasp)))
data$slope <- raster::extract(slope, st_transform(data, crs=projection(slope)))
data$tpi <- raster::extract(tpi, st_transform(data, crs=projection(tpi)))
```

```{r}
##extract habitat rap data to all points by yr
yrs <- data$yr
unique_yrs <- unique(yrs)
XYdata <- data

# prepare parallel processing
  no_cores <- detectCores()-1
  print(paste0("Initiating parallel processing on ", no_cores, " cores."))
  clust <- makeCluster(no_cores) 
  parallel::clusterExport(clust, envir=environment(),
                varlist=c("yrs","XYdata","unique_yrs",
                          "RAP_forbgrass_biomass", "RAP_treecov_list",
                          "RAP_shrubcov_list", "data"))

#forb grass biomass  
  # start parallel loop
  vals <- do.call(c, clusterApplyLB(clust, 1:length(unique_yrs), function(j){
    require("raster")
    require("sf")
      
      #grab raster matching year of data
      r <- RAP_forbgrass_biomass[[paste0("forb_grass_biomass_",
                                                  as.character(unique_yrs[[j]]))]]
    
      # extract the rap data 
      return(extract(r, st_transform(XYdata[XYdata$yr == unique_yrs[j],], 
                                     crs = projection(r))))   
    }))  
    # add column to original database
    data$forbgrass_biomass <- vals
  
#tree cover
  # start parallel loop
  vals <- do.call(c, clusterApplyLB(clust, 1:length(unique_yrs), function(j){
    require("raster")
    require("sf")
      
      #grab raster matching year of data
      r <- RAP_treecov_list[[paste0(as.character(unique_yrs[[j]]),
                                            "_Cover_Trees")]]
    
      # extract the rap data 
      return(extract(r, st_transform(XYdata[XYdata$yr == unique_yrs[j],], 
                                     crs = projection(r))))   
    }))  
   # add column to original database
    data$perc_treecov <- vals
    
#shrub cover
  # start parallel loop
  vals <- do.call(c, clusterApplyLB(clust, 1:length(unique_yrs), function(j){
    require("raster")
    require("sf")
      
      #grab raster matching year of data
      r <- RAP_shrubcov_list[[paste0(as.character(unique_yrs[[j]]),
                                            "_Cover_Shrubs")]]
    
      # extract the rap data 
      return(extract(r, st_transform(XYdata[XYdata$yr == unique_yrs[j],], 
                                     crs = projection(r))))   
    }))   
  
   # add column to original database
    data$perc_shrubcov <- vals
  
  # end parallell processing
  stopCluster(clust)
```

```{r}
#extract snodas snow depth by point- 2016-7/2021 data
source("Z:/Snodas/code/extract.snodas.R")
  data_s1 <- data %>% filter(date_only < as.Date("2021-08-01"))
  
  XYdata <- st_as_sf(data_s1, coords = c("x", "y"), crs = crs(data))

  XYdata <- extract.snodas(XYdata = XYdata, SNODASfolder = "Z:/Snodas/snowdepth",
                 datesname = "date")

  data_s1$snowdepth <- XYdata$Snodas_SnowDepth
  
#extract snodas snow depth by point- 2016-7/2021 data
  data_s2 <- data %>% filter(date_only >= as.Date("2021-08-01"))

  XYdata <- st_as_sf(data_s2, coords = c("x", "y"), crs = crs(data))

  XYdata <- extract.snodas(XYdata = XYdata, SNODASfolder = "C:/Users/mcaldwe2/OneDrive - University of Wyoming/Documents/UWyo/PhD project/HOTR-proj/Data/GIS data/snodas_082021to122021_snowdepth/",
                 datesname = "date")

  data_s2$snowdepth <- XYdata$Snodas_SnowDepth
  
  
data <- rbind(data_s1, data_s2)
```

```{r}
  #extract snodas swe by point- 2016-9/2021 data
source("Z:/Snodas/code/extract.snodas.R")
  data_s1 <- data %>% filter(date_only < as.Date("2021-08-01"))
  
  XYdata <- st_as_sf(data_s1, coords = c("x", "y"), crs = crs(data))

  XYdata <- extract.snodas(XYdata = XYdata, SNODASfolder = "Z:/Snodas/swe",
                 datesname = "date")

  data_s1$swe <- XYdata$Snodas_SWE
  
#extract snodas snow depth by point- 2016-7/2021 data
  data_s2 <- data %>% filter(date_only >= as.Date("2021-08-01"))

  XYdata <- st_as_sf(data_s2, coords = c("x", "y"), crs = crs(data))

  XYdata <- extract.snodas(XYdata = XYdata, SNODASfolder = "C:/Users/mcaldwe2/OneDrive - University of Wyoming/Documents/UWyo/PhD project/HOTR-proj/Data/GIS data/swe_9.21to12.21/",
                 datesname = "date")

  data_s2$swe <- XYdata$Snodas_SWE
  
  
data <- rbind(data_s1, data_s2)

```

#NDVI/greenup metrics extract to point

```{r}
#take data out of sf format, and into a simple data frame.
data <- data %>%
   mutate(x=st_coordinates(.)[,1],
         y=st_coordinates(.)[,2]) %>% 
  st_drop_geometry()

#load and run ndvi extract code
##extract max IRG date, maxNDVIdate, csumNDVImax, fittedVals (NDVI), IRGVals in loop
source("Z:/MODIS_NDVI/info/ndviEXTRACT.R")

ext_vars <- c("fittedVals", "IRGVals", "maxNDVIdate", "maxIRGdate", 
              "csumNDVImax")

for(i in 1:length(ext_vars)){
data$ne <- ndviEXTRACT(XYdata = data, NDVImetric = ext_vars[i],
                  NDVIfolder="Z:/MODIS_NDVI/Bischof_calculations/",
                        maxcpus=4, xname="x", yname="y", datesname="date", 
                  scaleIRG=TRUE,
                  xyCRS = CRS("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"))

#rename column
names(data)[names(data) == "ne"] <- ext_vars[i]
}

#rename fittedvals to NDVIVals
data <- data %>%
  rename("NDVIVals" = fittedVals)
```

```{r}
#convert data back to sf
data <- st_as_sf(data, coords = c("x", "y"))

#save data
saveRDS(data, "./Code output/individual_habitat_metrics/allindiv_gpspts_habextract.rds")
```

