---
title: "YNP ungulate RSFs Part B GIS Extraction"
author: "Molly Caldwell"
date: "3/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE)
knitr::opts_knit$set(root.dir = "~/UWyo/PhD project/YNP-ungulate-niche-proj/")
```

```{r}
#load packages
library(sf)
library(raster)
library(mapview)
library(tidyverse)
library(stringr)
library(move)
library(dummies)
library(lme4)
library(parallel)
library(lubridate)
```

#Load sampled RSFs environment
From part A code

```{r}
load("RSFs_AvailSampled.RData")

data_list <- data_pop_spp_seas
```

#Relate GIS to points

```{r}
#bring in all your GIS data
elev <- raster("~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/Elevation_meters_30m_gye.tif")
trasp <- raster("~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/Aspect_TRASP_30m_gye.tif")
slope <- raster("~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/Slope_degrees_30m_gye.tif")
tpi <- raster("~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/TPI_unitless_30m_gye.tif")


#RAP data (forbs grass biomass and %cover by land cover type per year)
RAP_ann_biomass_file_list <- list.files(path = "~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/", 
                        pattern = glob2rx("*Biomass*AnnualForbsGrasses*"),
                        full.names = TRUE)

RAP_per_biomass_file_list <- list.files(path = "~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/", 
                        pattern = glob2rx("*Biomass*PerennialForbsGrasses*"),
                        full.names = TRUE)

RAP_treecov_file_list <- list.files(path = "~/UWyo/PhD project/HOTR-proj/Data/GIS_data_clean/", 
                        pattern = glob2rx("*Cover_Trees*"),
                        full.names = TRUE)

RAP_ann_biomass_list <- list()
for(i in 1:length(RAP_ann_biomass_file_list)){
  print(i)
RAP_ann_biomass_list[[i]] <- raster(RAP_ann_biomass_file_list[[i]])
}

RAP_ann_biomass_names <- sub(".*RAP_gye_30m_reproj_", "", RAP_ann_biomass_file_list)
RAP_ann_biomass_names <- sub("*.tif", "", RAP_ann_biomass_names)
names(RAP_ann_biomass_list) <- RAP_ann_biomass_names

RAP_per_biomass_list <- list()
for(i in 1:length(RAP_per_biomass_file_list)){
  print(i)
RAP_per_biomass_list[[i]] <- raster(RAP_per_biomass_file_list[[i]])
}

RAP_per_biomass_names <- sub(".*RAP_gye_30m_reproj_", "", RAP_per_biomass_file_list)
RAP_per_biomass_names <- sub("*.tif", "", RAP_per_biomass_names)
names(RAP_per_biomass_list) <- RAP_per_biomass_names

RAP_treecov_list <- list()
for(i in 1:length(RAP_treecov_file_list)){
  print(i)
RAP_treecov_list[[i]] <- raster(RAP_treecov_file_list[[i]])
}

RAP_treecov_names <- sub(".*RAP_gye_30m_reproj_", "", RAP_treecov_file_list)
RAP_treecov_names <- sub("*.tif", "", RAP_treecov_names)
names(RAP_treecov_list) <- RAP_treecov_names
```

```{r}
#add perennial and annual grass and forb biomass rasters by year
RAP_forbgrass_biomass <- list()

for(i in 1:length(RAP_per_biomass_list)){
  print(paste0("i: ", i))
  
  biomass_stack <- stack(RAP_ann_biomass_list[[i]], RAP_per_biomass_list[[i]])
  ann_per_biomass <-  calc(biomass_stack, sum)
  
  RAP_forbgrass_biomass[[i]] <- ann_per_biomass
}

names(RAP_forbgrass_biomass) <- c("forb_grass_biomass_2016", 
                                  "forb_grass_biomass_2017",
                                  "forb_grass_biomass_2018",
                                  "forb_grass_biomass_2019",
                                  "forb_grass_biomass_2020",
                                  "forb_grass_biomass_2021")

```


```{r}
# extract GIS data to points by spp and season

for(i in 1:length(data_list)){
data_list[[i]]$elev <- raster::extract(elev, st_transform(data_list[[i]], crs=projection(elev)))
data_list[[i]]$trasp <- raster::extract(trasp, st_transform(data_list[[i]], crs=projection(trasp)))
data_list[[i]]$slope <- raster::extract(slope, st_transform(data_list[[i]], crs=projection(slope)))
data_list[[i]]$tpi <- raster::extract(tpi, st_transform(data_list[[i]], crs=projection(tpi)))

##extract rap data by yr
yrs <- data_list[[i]]$yr
unique_yrs <- unique(yrs)
XYdata <- data_list[[i]]

# prepare parallel processing
  no_cores <- detectCores()-1
  print(paste0("Initiating parallel processing on ", no_cores, " cores."))
  clust <- makeCluster(no_cores) 
  parallel::clusterExport(clust, envir=environment(),
                varlist=c("yrs","XYdata","unique_yrs",
                          "RAP_forbgrass_biomass"))
  
  # start parallel loop
  vals <- do.call(c, clusterApplyLB(clust, 1:length(unique_yrs), function(j){
    require("raster")
    require("sf")
      
      #grab raster matching year of data
      r <- RAP_forbgrass_biomass[[paste0("forb_grass_biomass_",
                                                  as.character(unique_yrs[[j]]))]]
    
      # extract the rap data 
      return(extract(r, st_transform(XYdata[XYdata$yr == unique_yrs[j],], 
                                     crs = projection(r))))   
    }))   # end of loop over unique yrs
  stopCluster(clust)
  
    # add column to original database
    data_list[[i]]$forbgrass_biomass <- vals
  
  # prepare parallel processing
  no_cores <- detectCores()-1
  print(paste0("Initiating parallel processing on ", no_cores, " cores."))
  clust <- makeCluster(no_cores) 
  parallel::clusterExport(clust, envir=environment(),
                varlist=c("yrs","XYdata","unique_yrs",
                          "RAP_treecov_list"))
  
  # start parallel loop
  vals <- do.call(c, clusterApplyLB(clust, 1:length(unique_yrs), function(j){
    require("raster")
    require("sf")
      
      #grab raster matching year of data
      r <- RAP_treecov_list[[paste0(as.character(unique_yrs[[j]]),
                                            "_Cover_Trees")]]
    
      # extract the rap data 
      return(extract(r, st_transform(XYdata[XYdata$yr == unique_yrs[j],], 
                                     crs = projection(r))))   
    }))   # end of loop over unique yrs
  stopCluster(clust)
  
   # add column to original database
    data_list[[i]]$perc_treecov <- vals
  
  }




#extract rap data by year of gps dates
# u_yrs <- unique(data_list[[i]]$yr)
#   data_yr_list <- list()
#   
#   for(j in 1:length(u_yrs)){
#     data_yr_list[[j]] <- data_list[[i]] %>% filter(yr == u_yrs[[j]])
#    
#      data_yr_list[[j]]$forbgrass_biomass <- raster::extract(RAP_forbgrass_biomass[[paste0("forb_grass_biomass_",
#                                                   as.character(u_yrs[[j]]))]], 
#                     st_transform(data_yr_list[[j]],
#                   crs=projection(RAP_forbgrass_biomass[[paste0("forb_grass_biomass_",
#                                                   as.character(u_yrs[[j]]))]])))
#     
#     data_yr_list[[j]]$perc_treecov <- raster::extract(RAP_treecov_list[[paste0(as.character(u_yrs[[j]])),
#                                                               "_Cover_Trees"]], 
#                     st_transform(data_yr_list[[j]],
#                   crs=projection(RAP_forbgrass_biomass[[paste0(as.character(u_yrs[[j]])),
#                                                               "_Cover_Trees"]])))
#   }
#   
#   #bind together each yr dataset as one list element
#   data_list[[i]] <- rlist::list.rbind(data_yr_list)


```

```{r}
#extract snodas snow depth to winter data using Jerod's extract snodas function
spp <- c("bighorn", "bison", "elk", "deer", "pronghorn") #loop by spp
source("Z:/Snodas/code/extract.snodas.R")

for(i in 1:length(spp)){
  XYdata <- st_as_sf(data_list[[paste0(spp[[i]], ".winter")]], coords = c("x", "y"), crs = crs(data))
  
  XYdata <- extract.snodas(XYdata = XYdata, SNODASfolder = "Z:/Snodas/snowdepth",
                 datesname = "date")
  
  data_list[[paste0(spp[[i]], ".winter")]]$snowdepth <- XYdata$Snodas_SnowDepth
  
}
```


```{r}
#remove your rasters to clean up your environment
rm(elev, trasp, slope, tpi)
```

#Prepare data for analysis

```{r}
#take databases out of sf format, and into a simple data frame.
for(i in 1:length(data_list)){
  
data_list[[i]] <- data_list[[i]] %>%
   mutate(x=st_coordinates(.)[,1],
         y=st_coordinates(.)[,2]) %>% 
  st_drop_geometry()
}
```

#Save environment

```{r}
# now that you've extracted your GIS data, write out your environment! ####
# save your environment so we can load it back up another time 
save.image("RSFs_VariablesExtracted.RData")
```











